# Generated by blender_mcp schemas builder
from __future__ import annotations
import json
from typing import Any, Dict, List, Literal, Optional, Tuple, Union
from pydantic import BaseModel, Field

class InspectBpyPathInput(BaseModel):
    path: str = Field(..., description="The Python/RNA data path to inspect")

class GetRNASchemaInput(BaseModel):
    rna_type_name: str = Field(..., description="The Blender RNA struct type name")

class ExecuteOperatorInput(BaseModel):
    operator: str = Field(..., description="Operator identifier")
    execution_context: Literal["EXEC_DEFAULT", "INVOKE_DEFAULT", "EXEC_REGION_WIN", "EXEC_SCREEN", "INVOKE_REGION_WIN"] = "EXEC_DEFAULT"
    kwargs: Dict[str, Any] = Field(default_factory=dict)
    context_override: Dict[str, Any] = Field(default_factory=dict)

class PropertyGetSetInput(BaseModel):
    path: str = Field(..., description="The data path on the target entity")
    value: Optional[Any] = Field(None, description="The value to assign")

class ScriptSandboxInput(BaseModel):
    script: str = Field(..., description="Python script body to execute")
    use_transaction_rollback: bool = Field(True, description="Whether to wrap in undo step")

class SceneManageInput(BaseModel):
    action: Literal["create", "switch", "delete", "configure", "list", "get_active"] = "list"
    scene_name: Optional[str] = None
    new_name: Optional[str] = None
    create_mode: Literal["NEW", "EMPTY", "LINK_COPY", "FULL_COPY", "LINK_OBJECT_DATA"] = "NEW"
    unit_system: Optional[Literal["METRIC", "IMPERIAL", "NONE"]] = None
    unit_length: Optional[str] = None
    unit_rotation: Optional[Literal["DEGREES", "RADIANS"]] = None
    unit_scale_length: Optional[float] = None
    gravity: Optional[List[float]] = None
    use_gravity: Optional[bool] = None
    active_camera_name: Optional[str] = None

class WorldManageInput(BaseModel):
    mode: Literal["HDRI", "SKY_TEXTURE", "COLOR", "VOLUMETRICS_ONLY", "GET_INFO"] = "GET_INFO"
    world_name: Optional[str] = None
    color: Optional[List[float]] = None
    strength: float = 1.0
    hdri_filepath: Optional[str] = None
    hdri_rotation_z: float = 0.0
    sky_type: Literal["NISHITA", "HOSEK_WILKIE", "PREETHAM"] = "NISHITA"
    sky_sun_intensity: float = 1.0
    sky_sun_elevation: Optional[float] = None
    sky_sun_rotation: Optional[float] = None
    volume_type: Literal["NONE", "SCATTER", "ABSORPTION", "PRINCIPLED"] = "NONE"
    volume_density: float = 0.01
    volume_color: Optional[List[float]] = None
    volume_anisotropy: float = 0.0

class ViewportManageInput(BaseModel):
    action: Literal["switch_workspace", "set_shading", "set_overlays", "set_clipping_lens", "set_cursor", "lock_view", "get_state"]
    workspace_name: Optional[str] = None
    shading_type: Optional[Literal["WIREFRAME", "SOLID", "MATERIAL", "RENDERED"]] = None
    shading_options: Optional[Dict[str, Any]] = None
    show_overlays: Optional[bool] = None
    overlay_toggles: Optional[Dict[str, bool]] = None
    clip_start: Optional[float] = None
    clip_end: Optional[float] = None
    lens: Optional[float] = None
    cursor_location: Optional[List[float]] = None
    cursor_rotation_euler: Optional[List[float]] = None
    lock_object_name: Optional[str] = None
    lock_cursor: Optional[bool] = None

class CameraManageInput(BaseModel):
    action: Literal["create", "update", "set_active", "get_properties", "delete"]
    camera_name: Optional[str] = None
    type: Literal["PERSP", "ORTHO", "PANO"] = "PERSP"
    focal_length: Optional[float] = None
    ortho_scale: Optional[float] = None
    sensor_fit: Optional[Literal["AUTO", "HORIZONTAL", "VERTICAL"]] = None
    sensor_width: Optional[float] = None
    sensor_height: Optional[float] = None
    clip_start: Optional[float] = None
    clip_end: Optional[float] = None
    shift_x: Optional[float] = None
    shift_y: Optional[float] = None
    dof: Optional[Dict[str, Any]] = None
    composition_guides: Optional[Dict[str, bool]] = None

class LightManageInput(BaseModel):
    action: Literal["create", "update", "delete", "get_properties", "set_linking"]
    light_name: Optional[str] = None
    type: Literal["POINT", "SUN", "SPOT", "AREA"] = "POINT"
    energy: Optional[float] = None
    color_type: Literal["RGB", "KELVIN"] = "RGB"
    color_rgb: Optional[List[float]] = None
    color_kelvin: Optional[float] = None
    radius: Optional[float] = None
    area_shape: Optional[Literal["SQUARE", "RECTANGLE", "DISK", "ELLIPSE"]] = None
    area_size_x: Optional[float] = None
    area_size_y: Optional[float] = None
    spot_size: Optional[float] = None
    spot_blend: Optional[float] = None
    spot_show_cone: Optional[bool] = None
    use_shadow: Optional[bool] = None
    light_linking: Optional[Dict[str, Any]] = None

class ObjectHierarchyInput(BaseModel):
    action: Literal["create", "delete", "duplicate", "rename", "set_parent", "clear_parent", "manipulate_parent_inverse"]
    names: Optional[List[str]] = None
    name: Optional[str] = None
    new_name: Optional[str] = None
    primitive_type: Optional[str] = None
    location: Optional[List[float]] = None
    rotation: Optional[List[float]] = None
    scale: Optional[List[float]] = None
    linked: bool = False
    delete_hierarchy: bool = False
    child_names: Optional[List[str]] = None
    parent_name: Optional[str] = None
    keep_transform: bool = True
    matrix_parent_inverse: Optional[List[List[float]]] = None

class CollectionManageInput(BaseModel):
    action: Literal["create", "delete", "move", "rename", "link_objects", "unlink_objects", "set_visibility"]
    name: str
    new_name: Optional[str] = None
    parent_collection: Optional[str] = None
    object_names: Optional[List[str]] = None
    unlink_from_all_others: bool = False
    hide_viewport: Optional[bool] = None
    hide_render: Optional[bool] = None
    hide_select: Optional[bool] = None
    color_tag: Optional[str] = None

class TransformObjectInput(BaseModel):
    name: str
    space: Literal["GLOBAL", "LOCAL", "PARENT"] = "GLOBAL"
    location: Optional[List[float]] = None
    relative_location: bool = False
    rotation_mode: Literal["XYZ", "XZY", "YXZ", "YZX", "ZXY", "ZYX", "QUATERNION", "AXIS_ANGLE"] = "XYZ"
    rotation: Optional[List[float]] = None
    rotation_in_degrees: bool = False
    relative_rotation: bool = False
    scale: Optional[List[float]] = None
    relative_scale: bool = False
    delta: bool = False

class ConstraintManageInput(BaseModel):
    action: Literal["add", "update", "remove", "get", "reorder"]
    object_name: str
    bone_name: Optional[str] = None
    constraint_name: Optional[str] = None
    constraint_type: Optional[str] = None
    config: Optional[Dict[str, Any]] = None
    new_index: Optional[int] = None

class MeshPrimitiveInput(BaseModel):
    primitive_type: Literal["CUBE", "UV_SPHERE", "ICO_SPHERE", "CYLINDER", "CONE", "TORUS", "GRID", "PLANE", "CIRCLE", "MONKEY", "EMPTY"] = "CUBE"
    name: Optional[str] = None
    location: Optional[List[float]] = None
    rotation: Optional[List[float]] = None
    scale: Optional[List[float]] = None
    size: float = 2.0
    radius: float = 1.0
    depth: float = 2.0
    segments: int = 32
    ring_count: int = 16
    subdivisions: int = 3

class MeshManipulateInput(BaseModel):
    object_name: str
    operation: Literal[
        "EXTRUDE_FACES", "BEVEL", "INSET_FACES", "SUBDIVIDE", "MERGE_VERTICES",
        "BRIDGE_EDGE_LOOPS", "DISSOLVE", "BOOLEAN", "RECALCULATE_NORMALS",
        "SET_SHADING", "CREATE_ELEMENTS", "DELETE_ELEMENTS"
    ]
    vertex_indices: Optional[List[int]] = None
    edge_indices: Optional[List[int]] = None
    face_indices: Optional[List[int]] = None
    translation: Optional[List[float]] = None
    offset: float = 0.2
    thickness: float = 0.0
    segments: int = 2
    profile: float = 0.5
    merge_type: Literal["DISTANCE", "CENTER", "COLLAPSE"] = "DISTANCE"
    boolean_target: Optional[str] = None
    boolean_operation: Literal["DIFFERENCE", "UNION", "INTERSECT"] = "DIFFERENCE"
    shading_mode: Optional[Literal["SMOOTH", "FLAT", "AUTO_SMOOTH"]] = None

class GeometryNodesInput(BaseModel):
    object_name: str
    modifier_name: str = "GeometryNodes"
    tree_name: Optional[str] = None
    nodes: Optional[List[Dict[str, Any]]] = None
    links: Optional[List[Dict[str, Any]]] = None

class MaterialManageInput(BaseModel):
    action: Literal["create", "delete", "duplicate", "assign", "set_use_nodes"]
    material_name: Optional[str] = None
    new_name: Optional[str] = None
    object_name: Optional[str] = None
    slot_index: Optional[int] = None
    face_indices: Optional[List[int]] = None
    use_nodes: bool = True

class ShaderNodeManageInput(BaseModel):
    action: Literal["create", "delete", "move"]
    material_name: str
    node_type: Optional[str] = None
    node_name: Optional[str] = None
    location: Optional[List[float]] = None
    group_name: Optional[str] = None

class UVUnwrapInput(BaseModel):
    object_name: str
    method: Literal["smart_project", "unwrap", "cube_project", "cylinder_project", "sphere_project", "lightmap_pack"] = "smart_project"
    angle_limit: float = 66.0
    island_margin: float = 0.02

class ModifierManageInput(BaseModel):
    object_name: str
    action: Literal["add", "remove", "apply", "reorder", "configure", "list"]
    modifier_name: Optional[str] = None
    modifier_type: Optional[str] = None
    new_index: Optional[int] = None
    properties: Optional[Dict[str, Any]] = None

class PhysicsSimulationInput(BaseModel):
    object_name: str
    physics_type: Literal["RIGID_BODY", "CLOTH", "COLLISION", "SOFT_BODY", "DYNAMIC_PAINT", "FLUID", "FORCE_FIELD"]
    action: Literal["enable", "disable", "configure", "bake"] = "enable"
    rigid_body: Optional[Dict[str, Any]] = None
    cloth: Optional[Dict[str, Any]] = None
    soft_body: Optional[Dict[str, Any]] = None
    fluid: Optional[Dict[str, Any]] = None
    force_field: Optional[Dict[str, Any]] = None

class ParticleSystemInput(BaseModel):
    object_name: str
    action: Literal["add", "remove", "configure", "list"]
    system_name: Optional[str] = None
    config: Optional[Dict[str, Any]] = None

class TimelineKeyframeInput(BaseModel):
    action: Literal["set_range", "set_current_frame", "set_fps", "insert_keyframe", "delete_keyframe", "list_fcurves", "modify_keyframe", "manage_driver", "manage_nla"]
    frame_start: Optional[int] = None
    frame_end: Optional[int] = None
    current_frame: Optional[int] = None
    fps: Optional[int] = None
    fps_base: Optional[float] = None
    target_type: Literal["OBJECT", "MATERIAL", "WORLD", "POSE_BONE", "NODE_TREE"] = "OBJECT"
    target_name: Optional[str] = None
    data_path: Optional[str] = None
    array_index: int = -1
    frame: Optional[float] = None
    value: Optional[Any] = None
    group: Optional[str] = None
    interpolation: Optional[str] = None

class ArmatureRiggingInput(BaseModel):
    action: Literal["create_armature", "pose_bone", "add_constraint", "pose_library"]
    armature_name: str
    location: Optional[List[float]] = None
    rotation_euler: Optional[List[float]] = None
    bones: Optional[List[Dict[str, Any]]] = None
    bone_name: Optional[str] = None
    bone_transforms: Optional[Dict[str, Any]] = None
    constraint_type: Optional[str] = None
    constraint_config: Optional[Dict[str, Any]] = None

class RenderConfigureInput(BaseModel):
    engine: Literal["CYCLES", "BLENDER_EEVEE_NEXT", "BLENDER_EEVEE", "BLENDER_WORKBENCH"] = "CYCLES"
    device_type: Literal["CPU", "GPU"] = "GPU"
    render_samples: int = 128
    viewport_samples: int = 32
    use_noise_threshold: bool = True
    noise_threshold: float = 0.01
    bounces: Optional[Dict[str, int]] = None

class RenderOutputPassesInput(BaseModel):
    resolution_x: int = 1920
    resolution_y: int = 1080
    resolution_percentage: int = 100
    fps: int = 24
    output_filepath: str = "//render_output/render_"
    file_format: str = "PNG"
    passes: Optional[Dict[str, bool]] = None

class ColorManagementInput(BaseModel):
    display_device: str = "sRGB"
    view_transform: str = "AgX"
    look: str = "None"
    exposure: float = 0.0
    gamma: float = 1.0

class CompositorManageInput(BaseModel):
    action: Literal["inspect", "enable", "clear", "add_node", "remove_node", "link", "set_socket_value"]
    node_type: Optional[str] = None
    node_name: Optional[str] = None
    location: Optional[List[float]] = None
    from_node: Optional[str] = None
    from_socket: Optional[str] = None
    to_node: Optional[str] = None
    to_socket: Optional[str] = None

class CaptureRenderInput(BaseModel):
    mode: Literal["STILL", "ANIMATION", "VIEWPORT_SCREENSHOT"] = "STILL"
    camera_name: Optional[str] = None
    frame_start: Optional[int] = None
    frame_end: Optional[int] = None
    shading_mode: Literal["WIREFRAME", "SOLID", "MATERIAL", "RENDERED"] = "RENDERED"
    show_overlays: bool = False
    output_path: Optional[str] = None
    return_base64: bool = True

class UserPreferencesInput(BaseModel):
    category: Literal["system", "interface", "view", "filepaths", "keymap", "experimental", "all"] = "system"
    action: Literal["get", "set"] = "get"
    settings: Optional[Dict[str, Any]] = None

class AddonManageInput(BaseModel):
    module_name: str
    action: Literal["enable", "disable", "install", "check_status"]
    filepath: Optional[str] = None

class ExternalDataInput(BaseModel):
    action: Literal["pack_all", "unpack_all", "find_missing", "make_paths_relative", "make_paths_absolute"]
    directory: Optional[str] = None

class UniversalIOInput(BaseModel):
    format: Literal["fbx", "obj", "gltf", "glb", "usd", "abc", "stl", "ply", "svg", "bvh", "dae"]
    mode: Literal["import", "export"]
    filepath: str
    options: Optional[Dict[str, Any]] = None

class MCPResponse(BaseModel):
    status: Literal["success", "error"] = "success"
    result: Optional[Dict[str, Any]] = None
    error: Optional[str] = None
    traceback: Optional[str] = None
